### ISSUE TITLE
FR - Support TypeId and SubtypeId in searches

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#1]
Plugin already has blockpairnames which is great, but it would also be really nice to support TypeId and SubtypeId for finding blocks.

A use case example would be paired with the Tiered Tech mod -- to get a sum of all Refineries with say, findblocks, we need to check 5 different BlockPairNames ("Blast Furnace","Refinery","Refinery[2x,4x,8x]"). If we could instead of search based on TypeID it would be more user friendly

**Comment by LordTylus** [comment]
Hi,

thank you for the suggestion. 

Its a very good idea and I could see quite a few use cases for that. I don't know when I will be able to implement it. But I will put it on the list.

**Comment by LordTylus** [comment]
As of Version 1.1.6.0 you can use

!listblocks all -findby=type or subtype or blockpair
to list blocky by type. 

however !listblocks limited will only work with blockpair

Also you can use
!findblock Thrust -findby=type

which will do exactly what you want show all thrusters.
