### ISSUE TITLE
Loophole with !fixship to get into spectator cam

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#10]
If you time it just right and use !fixship and manage to sneak into the cockpit of the ship before it gets cut (takes some luck, a big, ship, and some lag to pull off), when the ship is cut you get free spectator cam you can use to fly around the whole world as you wish

If sim is around 0.8 and my ping is >150 on the f3 screen in game I can pull it off like 1/8 times or so

**Comment by LordTylus** [comment]
As discussed a while back there is nothing I can do against it right now.

made a Bugreport at 
https://support.keenswh.com/spaceengineers/pc/topic/modapi-players-can-still-enter-cockpit-of-ship-which-is-marked-for-close

therefore closed

Edit: Also this is PCU Transferrer not Shipfixer
