### ISSUE TITLE
Grid name with spaces

### ISSUE THREAD

**Issue by martino-giorgi** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#12]
Currently, it's not possible to perform commands with grids that have spaces in their name unless the player is pointing to the grid.

An easy fix may be the usage of a special character before and after the name of the grid in the command so you can trim the string between those two characters.

!protect "my grid"

**Comment by LordTylus** [comment]
Hi, this is exactly how it already works. Writing names with spaces on quotation marks is already delivered by torch so I didn't even need to implement such feature.

However grid names are case-sensitive of course. which is to reduce the amount of possible conflicts. 

Speaking of which: if there are multiple grids with the exact same name it won't work either to prevent you from accidentally changing the wrong grid.

Feel free to retest it and if you still cannot get it to work please provide detailed stwps to reproduce as we then would be looking for a bug in the plugin

**Comment by LordTylus** [comment]
I just verified it myself:
![image](https://user-images.githubusercontent.com/22499516/106379366-c0cab680-63ab-11eb-8f11-0554983703e0.png)
Works fine

If there is a name conflict btw it outputs:
![image](https://user-images.githubusercontent.com/22499516/106379385-e8218380-63ab-11eb-86e7-66fd859a177a.png)
