### ISSUE TITLE
Recharge Batteries and Fill Hydrogen Tanks

### ISSUE THREAD

**Issue by badbambam** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#13]
Hi, this is a request to add !recharge <entity> <Battery # or ALL> <0-100> ( by percentage)
and  similar for hydrogen tanks !refillh <entity> <Tank # or ALL> <0-100> (by percentage)

Thank You

BadBamBam

**Comment by LordTylus** [comment]
Yep is a good idea

I can see that being used for everything that can hold charge
Batteries,
O2 Tanks
H2 Tanks
Jump Drives

no guarantee it easily works on all of them. But Ill find that out ^^ at a given time. Probably nest weekend

**Comment by LordTylus** [comment]
Added in 1.1.11.0

- !recharge <battery|jumpdrive|o2tank|h2tank|tank> \<percentage>
-- Recharges/Fills the given blocks on the looked at grid to the given percentage
- !recharge grid \<gridname> \<battery|jumpdrive|o2tank|h2tank|tank> \<percentage>
-- Recharges/Fills the given blocks on the given grid to the given percentage

Example:

- !recharge o2tank 
-- recharges all o2 tanks on the looked at grid to 100%
- !recharge h2tank 75
-- recharges all h2 tanks on the looked at grid to 75%
- !recharge grid "Static Grid 5536" tank 50
-- recharges all o2 and h2 tanks on static grid 5536 to 50%
- !recharge jumpdrive
-- immediately recharges all jumpdrives on looked at grid. 

everything that requires looking at grids of course wont work when typing commands via discord bridge or torch UI
