### ISSUE TITLE
Unable to !transfer with block limits set to 0

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#15]
The issue of not being able to use !transfer when block limit mode is per player and max blocks is set to 0 is back - previously here.
Unsure in the original issue if we had any block limits enabled or if it was just mad they were set to 0
https://github.com/LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer/issues/4

https://i.imgur.com/nYpsSWJ.png
https://i.imgur.com/LVXzSD0.png

**Comment by kontu** [comment]
[Vanilla.zip](https://github.com/LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer/files/6317427/Vanilla.zip)
Here's a save (and a se-dedi.cfg file) that I can reproduce with trying to transfer to say, Skinface

**Comment by LordTylus** [comment]
Fixed in 1.1.11.2
