### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by blthlt** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#3]
Anyway we can get this to export the data to a file?

**Comment by LordTylus** [comment]
Hello, thank you for your request.

Unfortunately this is nowhere near enough information for me to guess what you actually want to export. Could you please elaborate a bit more on that?

What data do you want exported to a file? Whats the usecase/scenario you want to have data exported for? What data formats you would need? etc.

Personally I dont see the need for any export function so I dont have immediate plans to write anything like that. However without more information its definitely never becoming a thing.

**Comment by blthlt** [comment]
For instance, !listblocks all -player=hobbs, will list all the blocks he has.  I want to have a way to have this exported so it can be used in a way to show the naughty players who've went over the server limits on the server website or discord.  I guess format csv would work so it could be imported into a database or manipulated otherwise.

**Comment by LordTylus** [comment]
I see,

sounds doable, but very low in priority so I cannot say when Ill come around to implement that.

**Comment by Youfoundme001** [comment]
Hello LordTylus,
I was wondering if you had any update on exporting this information.  We currently use this plugin on the Draconis server cluster.  We are looking to implement a way to do multi server reports by aggregating the information from multiple servers to help us in detecting block counts across the entire cluster.  If this is something you are interested in doing could it be configured to do a -log argument or something similar so its not an automatic feature?

-Thank you for your time today.

**Comment by kontu** [comment]
YFM and I want to use this to build a bot that essentially can do cross-server block count checks.
We would run:
!findblock refinery -findby=type -metric=owner
on server A and server B, combine the lists, and find total block counts for players.

Our cluster allows transit between servers, but our block limits are clusterwide, and this would go very very far in helping us enforce and track it

**Comment by LordTylus** [comment]
Hello dear Friends,

I added a -export parameter to !listblocks and !findblock which then exports the data to a csv file in your instances folder

F:\SE\Space Engineers\Server\torch-server\Instance\ExportedStatistics

!findblock refinery -findby=type -metric=owner -export=refineries

> Id;Name;Faction;Owner;Block Count
> 144115188075855943;Stercorario;4RE;;5
> 144115188075855929;Starhammer;BRD;;4
> 144115188075855965;Escanor;;;3

!listblocks limited -export=listall

> Block Name;Block Count;Block Limit;PCU Count
> Drill;120;12;0
> OxygenGenerator;72;12;0
> Assembler;20;12;0

!listblocks all -pcu -export=listallwithpcu

> Block Name;Block Count;PCU Count
> LightArmorBlock;23155;23155
> LightArmorSlope;1641;1641
> LargeBlockArmorSlope2Base;860;860

@kontu for your usecase I also added a new command !listallblocks which outputs like how many of each Blocks a player in your world has. It can be used for displaying data in terminal, dialoge window and of course also be exported

!listallblocks -metric=owner -export=allplayers

> Id;Name;Faction;Block Name;Block Count;PCU Count
> 144115188075855905;[ATF]-Warground;;Battery1x1Block;1;15
> 144115188075855905;[ATF]-Warground;;BatteryBlock;1;15
> 144115188075855930;=DBAT= DDragon;DAG;Antenna;1;100
> 144115188075855930;=DBAT= DDragon;DAG;Assembler;2;80
> 144115188075855930;=DBAT= DDragon;DAG;BatteryBlock;10;150

Of course on gigantic worlds there may be a performance impact I could not measure just yet. But I tried to improve it as much as possible in advance.

the name you put in -export= you can define yourselves. The file extension is added automatically. if you put one yourselves it will end up having two of them 

-export=lol.csv would be converted to lol.csv.csv

![image](https://user-images.githubusercontent.com/22499516/89710514-1a65a180-d984-11ea-932d-fef717891e0e.png)

If you export to the same file the previous one would be overwritten without any kind of confirmation. This allows automated scripts to just regulary check and can keep the same name. 

Changes can be played around with in PCU Transferrer v1.1.10.0
