### ISSUE TITLE
Request: Allow "listblocks" -grid filtering to accept EntityID

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#5]
It would be nice if "listblocks" allowed for EntityID instead of only grid name
Grid I want to look at : 
`7 106386066849741728 Delphic Starbase One - Owned by: SeliG [DEL]`

This command works:
` !listblocks all -findby=type -orderby=name "-grid=Delphic Starbase One"`

This command does not, whether i have quotes around -grid or not
 `!listblocks all -findby=type -orderby=name "-grid=106386066849741728"`

entityID: https://i.imgur.com/gnYggjK.png
GridName: https://i.imgur.com/mX6puwI.png

**Comment by LordTylus** [comment]
Ahh Yes this is something I have been planning to add to ALL commands and ALL plugins that I have.

because often when looking for a grid like a Respawn Pod there may be naming conflicts.

I am usure on when I am able to add it, but ill put it on the list

**Comment by LordTylus** [comment]
!listblocks can now filter by gridname with wildcard. for example -grid=Del*One
!listblocks can now filter by entity Id (wildcard also supported) -grid=106386066849741728 or -grid=106*728

!listgrids, !listgridsauthor, !listgidsowner have now a -id parameter which allows you to optionally print the IDs of these grids in case you need them.

Can be used in v1.1.8.2
