### ISSUE TITLE
Use steamid and playername

### ISSUE THREAD

**Issue by bodyboarder2528** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#7]
hi,

I have a player with a name that uses emotes as its name, therefore i cant use pcu transfer to findblock as it needs their playername. If we can use their steam id then it will be more beneficial.

**Comment by LordTylus** [comment]
In 1.1.9.0 you will be able to use Name, SteamId and IdentityId if you feel like it for all commands withing PCU Transferrer that allow you to enter a Playername

So you can also use it for !transfer commands.
