### ISSUE TITLE
Feature request : Make faction removal from gridcleanup optional

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#9]
We have use cases where we'd like to remove ownership of blocks from players who are smallowners of grids but haven't been on in say, two weeks -- but we don't want  them removed from their factions. 

Would you be willing to add a command switch to !gridcleanup to toggle off removal from factions?

**Comment by LordTylus** [comment]
You can now prevent that from happening when adding -keepfactions at the end of command

!gridcleanup 10 -keepfactions

Will be published in 1.1.8.9
